#!/bin/bash
# Generates chuso1800_deploy.lua, the single Stormworks-pasteable LUA node
# script: ../../lib/state_sync.lua (the generic sync driver) + src/chuso1800_core.lua
# (wrapped as a local module, since Stormworks has no `require`) + bridge.lua
# (the calculateTick adapter between the two).
#
# Run this after editing lib/state_sync.lua, src/chuso1800_core.lua, or
# bridge.lua -- chuso1800_deploy.lua is checked in so it can be copy-pasted
# directly without running this script, but it must be regenerated whenever
# any of its three sources change.
#
# Usage: ./build.sh   (run from this directory)

set -euo pipefail
cd "$(dirname "$0")"

LIB_STATE_SYNC="../../lib/state_sync.lua"
CORE="../src/chuso1800_core.lua"
BRIDGE="bridge.lua"
OUT="chuso1800_deploy.lua"

{
  echo "-- AUTO-GENERATED by deploy/build.sh -- do not edit directly."
  echo "-- Sources: lib/state_sync.lua + src/chuso1800_core.lua + deploy/bridge.lua"
  echo "-- Paste this whole file into a single Stormworks LUA node."
  echo
  echo "----------------------------------------------------------------------"
  echo "-- lib/state_sync.lua"
  echo "----------------------------------------------------------------------"
  cat "$LIB_STATE_SYNC"
  echo
  echo "----------------------------------------------------------------------"
  echo "-- src/chuso1800_core.lua (wrapped as a local module; Stormworks has"
  echo "-- no require, and a top-level 'return M' mid-file would otherwise be"
  echo "-- a syntax error once concatenated)"
  echo "----------------------------------------------------------------------"
  echo "local core = (function()"
  cat "$CORE"
  echo "end)()"
  echo
  echo "----------------------------------------------------------------------"
  echo "-- deploy/bridge.lua"
  echo "----------------------------------------------------------------------"
  cat "$BRIDGE"
} > "$OUT"

echo "Wrote $OUT"
