#!/usr/bin/env node
// tools/route-data-sync/vendor/route_data.snapshot.json から、
// CHUSO2000_Driver_Assistance_IV の n61.lua/n141.lua が使うテーブルだけを
// 抜き出し、storm-lua-minify式 dofile(...) で取り込める Lua モジュールを
// 2本生成する。
//
// - route_data_arc.lua      (n141向け): link_tbl, arc_type_tbl, arc_trk_tbl
// - route_data_position.lua (n61向け) : link_tbl, stop_type_tbl, coord_tbl,
//                                        meterage, not4srv, doorcut_tbl
//
// dofile(...) はstorm-lua-minifyによってその場に生の文として展開されるため、
// 出力は `local` 宣言なし・`return` なしのグローバル代入のみとする
// (lib/state_sync.lua と同じ流儀。LUA_CODING_GUIDE.md参照)。
// link_tbl は両モジュールに重複して持たせる(ノードごとの文字数節約を優先。
// 1モジュールに全テーブルを詰めると両ノードとも不要なテーブルまで
// dofile展開で抱え込むことになるため)。
//
// 使い方: node tools/route-data-sync/generate.mjs

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const snapshotPath = path.join(here, "vendor", "route_data.snapshot.json");
const metaPath = path.join(here, "vendor", "route_data.snapshot.meta.json");
const outDir = path.resolve(here, "../../CHUSO2000_Driver_Assistance_IV/src");

// ---- route_data.json の読み込み・平坦化 ----

function load(snapshotPath) {
  const data = JSON.parse(fs.readFileSync(snapshotPath, "utf8"));
  const types = data.types ?? [];
  const stations = data.stations ?? [];
  const tracks = stations.flatMap((s) => s.tracks ?? []);
  return { types, stations, tracks };
}

// ---- Teinishi氏 lua/route_data_lua.py の該当関数と同じ変換 ----

function createLinkTable(tracks) {
  const table = {};
  for (const t of tracks) {
    if (t.inbound) table[2 * t.id - 1] = t.inbound;
    if (t.outbound) table[2 * t.id] = t.outbound;
  }
  return table;
}

function createStopTypeTable(stations) {
  const table = {};
  for (const s of stations) {
    for (const t of s.tracks ?? []) table[t.id] = s.stopTypes ?? [];
  }
  return table;
}

function createCoordinateTable(tracks) {
  const table = {};
  for (const t of tracks) if (t.coordinate) table[t.id] = t.coordinate;
  return table;
}

// route_data_lua.py にはまだ無い関数(meterageはJSON側に既にあるが未出力
// だったため、このリポジトリ用にここで追加)。
function createMeterageTable(tracks) {
  const table = {};
  for (const t of tracks) if (t.meterage !== undefined) table[t.id] = t.meterage;
  return table;
}

function createNotForServiceTable(tracks) {
  const table = {};
  for (const t of tracks) if (t.notForService) table[t.id] = 1;
  return table;
}

function createDoorcutTable(tracks) {
  const pick = (d = {}) => {
    const r = {};
    if (d.inbound !== undefined) r.i = d.inbound;
    if (d.middle !== undefined) r.m = d.middle;
    if (d.outbound !== undefined) r.o = d.outbound;
    return r;
  };
  const table = {};
  for (const t of tracks) {
    if (t.doorcut) {
      table[t.id] = [pick(t.doorcut.inbound), pick(t.doorcut.outbound)];
    }
  }
  return table;
}

function createArcTypeTable(types) {
  const table = {};
  for (const ty of types) if (ty.arc !== undefined) table[ty.id] = ty.arc;
  return table;
}

function createArcTrackTable(tracks) {
  const table = {};
  for (const t of tracks) if (t.arc !== undefined) table[t.id] = t.arc;
  return table;
}

// ---- Lua リテラル直列化 (tools/sw-net-sim/build.mjs の luaValue に準拠) ----

function luaNumberOrArcValue(v) {
  if (v === undefined || v === null) return "nil";
  if (Array.isArray(v)) return "{" + v.map((x) => String(x)).join(",") + "}";
  if (typeof v === "object" && "min" in v && "max" in v) return `{min=${v.min},max=${v.max}}`;
  return String(v);
}

// 1..maxId の密な配列として出力する(欠番はnil)。
function denseArrayLiteral(table, maxId, valueToLua) {
  const parts = [];
  for (let i = 1; i <= maxId; i++) parts.push(valueToLua(table[i]));
  return "{" + parts.join(",") + "}";
}

function linkTableLiteral(table, maxId) {
  const parts = [];
  for (let i = 1; i <= maxId * 2; i++) {
    const v = table[i];
    parts.push(v ? "{" + v.join(",") + "}" : "nil");
  }
  return "{" + parts.join(",") + "}";
}

function sparseObjectLiteral(table, valueToLua) {
  const entries = Object.keys(table)
    .map(Number)
    .sort((a, b) => a - b)
    .map((k) => `[${k}]=${valueToLua(table[k])}`);
  return "{" + entries.join(",") + "}";
}

function doorcutEntryLiteral(entry) {
  const fields = Object.entries(entry)
    .map(([k, v]) => `${k}=${v}`)
    .join(",");
  return "{" + fields + "}";
}

function doorcutTableLiteral(table) {
  return sparseObjectLiteral(table, (pair) => "{" + pair.map(doorcutEntryLiteral).join(",") + "}");
}

// ---- モジュール組み立て ----

function header(meta, tableNames) {
  return [
    `-- AUTO-GENERATED by tools/route-data-sync/generate.mjs from route_data.snapshot.json`,
    `-- source: ${meta.source} (${meta.path} @ ${meta.commit}, fetched ${meta.fetchedAt})`,
    `-- Do not edit by hand; re-run \`pnpm run gen:route-data\` instead.`,
    `-- dofile-target module (no local/return): ${tableNames.join(", ")}`,
    "",
  ].join("\n");
}

function main() {
  if (!fs.existsSync(snapshotPath)) {
    console.error(`snapshot not found at ${snapshotPath} -- run \`pnpm run sync:route-data\` first.`);
    process.exit(1);
  }
  const meta = JSON.parse(fs.readFileSync(metaPath, "utf8"));
  const { types, stations, tracks } = load(snapshotPath);

  const maxTrackId = Math.max(...tracks.map((t) => t.id));
  const maxTypeId = Math.max(...types.map((t) => t.id));

  const linkTable = createLinkTable(tracks);
  const stopTypeTable = createStopTypeTable(stations);
  const coordTable = createCoordinateTable(tracks);
  const meterageTable = createMeterageTable(tracks);
  const notForServiceTable = createNotForServiceTable(tracks);
  const doorcutTable = createDoorcutTable(tracks);
  const arcTypeTable = createArcTypeTable(types);
  const arcTrackTable = createArcTrackTable(tracks);

  fs.mkdirSync(outDir, { recursive: true });

  const arcModule =
    header(meta, ["link_tbl", "arc_type_tbl", "arc_trk_tbl"]) +
    `link_tbl=${linkTableLiteral(linkTable, maxTrackId)}\n` +
    `arc_type_tbl=${denseArrayLiteral(arcTypeTable, maxTypeId, luaNumberOrArcValue)}\n` +
    `arc_trk_tbl=${denseArrayLiteral(arcTrackTable, maxTrackId, luaNumberOrArcValue)}\n`;
  fs.writeFileSync(path.join(outDir, "route_data_arc.lua"), arcModule);

  const positionModule =
    header(meta, ["link_tbl", "stop_type_tbl", "coord_tbl", "meterage", "not4srv", "doorcut_tbl"]) +
    `link_tbl=${linkTableLiteral(linkTable, maxTrackId)}\n` +
    `stop_type_tbl=${denseArrayLiteral(stopTypeTable, maxTrackId, (v) => (v ? "{" + v.join(",") + "}" : "nil"))}\n` +
    `coord_tbl=${denseArrayLiteral(coordTable, maxTrackId, (v) => (v ? "{" + v.join(",") + "}" : "nil"))}\n` +
    `meterage=${denseArrayLiteral(meterageTable, maxTrackId, (v) => (v === undefined ? "nil" : String(v)))}\n` +
    `not4srv=${sparseObjectLiteral(notForServiceTable, (v) => String(v))}\n` +
    `doorcut_tbl=${doorcutTableLiteral(doorcutTable)}\n`;
  fs.writeFileSync(path.join(outDir, "route_data_position.lua"), positionModule);

  console.error(`wrote ${path.relative(process.cwd(), path.join(outDir, "route_data_arc.lua"))}`);
  console.error(`wrote ${path.relative(process.cwd(), path.join(outDir, "route_data_position.lua"))}`);
  console.error(`tracks: ${tracks.length} (max id ${maxTrackId}), types: ${types.length} (max id ${maxTypeId})`);
}

main();
