#!/usr/bin/env node
// sw-net (.sw-net) を storm-microcontroller-language でパースし、
// lib/sw_net_sim.lua が dofile で直接読み込める Lua テーブルリテラルへ変換する。
//
// 使い方: node tools/sw-net-sim/build.mjs <input.sw-net> <output.graph.lua>
//
// 実機との既知の齟齬（SPEC.md §2 / LEGACY_SPEC_CORRECTIONS.md §3-4）を
// ここで補正する。main.sw-net 自体は書き換えない（原稿のまま）。

import { parseSwNetDocument } from "storm-microcontroller-language";
import fs from "node:fs";
import path from "node:path";

const THRESHOLD_MAX_1_TO_0 = new Set([
  "catenary_active_thresh",
  "position_changing",
  "notch_active",
  "notch_fb_ge1",
  "regen_available",
  "direction_nonzero",
]);

// SPEC.md §2: 「Physics Sensor N9への結線は、元sw-net上では入力指定が欠けている。
// 実機結線では車両前後速度を読むものとして扱う」-- 該当ノードの composite
// 入力を、そのポート名へ明示的に補完する。
const MISSING_COMPOSITE_INPUT_FALLBACK = {
  speed: "Phyics Sensor [+Z is front]",
};

function unwrapLiteral(expr) {
  if (!expr) return null;
  switch (expr.kind) {
    case "number":
      return { kind: "lit", value: expr.value };
    case "boolean":
      return { kind: "lit", value: expr.value };
    case "string":
      return { kind: "port", value: expr.value };
    case "identifier":
      return { kind: "sig", value: expr.value };
    case "null":
      return { kind: "lit", value: null };
    default:
      throw new Error(`unknown expression kind: ${expr.kind}`);
  }
}

function unwrapAttrLiteral(expr) {
  switch (expr.kind) {
    case "number":
    case "boolean":
      return expr.value;
    case "string":
      return expr.value;
    case "null":
      return null;
    default:
      throw new Error(`unexpected attribute expression kind: ${expr.kind}`);
  }
}

function luaString(s) {
  return '"' + String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n") + '"';
}

function luaValue(v) {
  if (v === null || v === undefined) return "nil";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "string") return luaString(v);
  throw new Error(`cannot serialize value: ${JSON.stringify(v)}`);
}

function buildGraph(swNetPath) {
  const text = fs.readFileSync(swNetPath, "utf8");
  const sourceName = path.basename(swNetPath);
  const doc = parseSwNetDocument(text, { sourceName });
  if (doc.modules.length !== 1) {
    throw new Error(
      `expected exactly 1 module, found ${doc.modules.length} (submodule/use composition is not supported by this simulator)`
    );
  }
  const mod = doc.modules[0];

  const ports = mod.ports.map((p) => ({
    direction: p.direction,
    name: p.name,
    signal: p.signal,
  }));

  const nodes = [];
  for (const stmt of mod.statements) {
    if (stmt.kind !== "inst") {
      throw new Error(`unsupported statement kind '${stmt.kind}' (use-statements are not supported)`);
    }
    const attrs = {};
    for (const a of stmt.attributes) attrs[a.key] = unwrapAttrLiteral(a.value);

    if (stmt.typeId === "THRESHOLD" && THRESHOLD_MAX_1_TO_0.has(stmt.instanceId)) {
      if (attrs.max !== 1) {
        throw new Error(
          `expected ${stmt.instanceId} to have literal max=1 before correction, got ${attrs.max}`
        );
      }
      attrs.max = 0;
    }

    const inputs = {};
    for (const i of stmt.inputs) inputs[i.key] = unwrapLiteral(i.value);

    const fallbackPort = MISSING_COMPOSITE_INPUT_FALLBACK[stmt.instanceId];
    if (fallbackPort && !inputs.composite) {
      inputs.composite = { kind: "port", value: fallbackPort };
    }

    const outputs = {};
    for (const o of stmt.outputs) outputs[o.key] = unwrapLiteral(o.value);

    nodes.push({
      id: stmt.instanceId,
      type: stmt.typeId,
      attrs,
      inputs,
      outputs,
    });
  }

  return { sourceName, ports, nodes };
}

function serializeGraph(graph) {
  const lines = [];
  lines.push("-- AUTO-GENERATED by tools/sw-net-sim/build.mjs from " + graph.sourceName);
  lines.push("-- Do not edit by hand; re-run the build script instead.");
  lines.push("return {");
  lines.push(`  source = ${luaString(graph.sourceName)},`);
  lines.push("  ports = {");
  for (const p of graph.ports) {
    lines.push(
      `    { direction = ${luaString(p.direction)}, name = ${luaString(p.name)}, signal = ${luaString(p.signal)} },`
    );
  }
  lines.push("  },");
  lines.push("  nodes = {");
  for (const n of graph.nodes) {
    lines.push(`    {`);
    lines.push(`      id = ${luaString(n.id)}, type = ${luaString(n.type)},`);
    lines.push(`      attrs = {`);
    for (const [k, v] of Object.entries(n.attrs)) {
      lines.push(`        ${k} = ${luaValue(v)},`);
    }
    lines.push(`      },`);
    lines.push(`      inputs = {`);
    for (const [k, v] of Object.entries(n.inputs)) {
      lines.push(`        ${k} = { ${v.kind} = ${luaValue(v.value)} },`);
    }
    lines.push(`      },`);
    lines.push(`      outputs = {`);
    for (const [k, v] of Object.entries(n.outputs)) {
      lines.push(`        ${k} = { ${v.kind} = ${luaValue(v.value)} },`);
    }
    lines.push(`      },`);
    lines.push(`    },`);
  }
  lines.push("  },");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function main() {
  const [, , inputArg, outputArg] = process.argv;
  if (!inputArg || !outputArg) {
    console.error("usage: node tools/sw-net-sim/build.mjs <input.sw-net> <output.graph.lua>");
    process.exit(1);
  }
  const graph = buildGraph(inputArg);
  const lua = serializeGraph(graph);
  fs.writeFileSync(outputArg, lua);
  console.error(
    `wrote ${outputArg} (${graph.nodes.length} nodes, ${graph.ports.length} ports) from ${inputArg}`
  );
}

main();
