-- AUTO-GENERATED by tools/sw-net-sim/build.mjs from main.sw-net
-- Do not edit by hand; re-run the build script instead.
return {
  source = "main.sw-net",
  ports = {
    { direction = "in", name = "Phyics Sensor [+Z is front]", signal = "composite" },
    { direction = "in", name = "Catenary Line Voltage [V]", signal = "number" },
    { direction = "in", name = "SAP [atm]", signal = "number" },
    { direction = "out", name = "DANRYU", signal = "boolean" },
    { direction = "out", name = "cam", signal = "boolean" },
    { direction = "out", name = "W", signal = "number" },
    { direction = "in", name = "Controller Stop", signal = "boolean" },
    { direction = "in", name = "BP [atm]", signal = "number" },
    { direction = "out", name = "BC target [atm]", signal = "number" },
    { direction = "in", name = "Simple IF", signal = "composite" },
    { direction = "in", name = "Extended IF", signal = "composite" },
    { direction = "out", name = "Momelink-A", signal = "composite" },
    { direction = "in", name = "BC [atm abs]", signal = "number" },
    { direction = "in", name = "Momelink inner unit", signal = "composite" },
    { direction = "in", name = "MR [atm abs]", signal = "number" },
    { direction = "out", name = "Rolling Stock Status", signal = "composite" },
  },
  nodes = {
    {
      id = "catenary_rated_voltage", type = "CONST",
      attrs = {
        value = 1500,
      },
      inputs = {
      },
      outputs = {
        value = { sig = "catenary_rated_voltage_value" },
      },
    },
    {
      id = "catenary_voltage_toggle", type = "PROPERTY_TOGGLE",
      attrs = {
        label = "",
        on_label = "On",
        off_label = "Off",
        n = "Catenary Line Voltage",
        v = true,
      },
      inputs = {
      },
      outputs = {
        out = { sig = "catenary_voltage_toggle_out" },
      },
    },
    {
      id = "catenary_active_thresh", type = "THRESHOLD",
      attrs = {
        min = 0,
        max = 0,
      },
      inputs = {
        value = { port = "Catenary Line Voltage [V]" },
      },
      outputs = {
        out = { sig = "catenary_active_thresh_out" },
      },
    },
    {
      id = "catenary_inactive", type = "NOT",
      attrs = {
      },
      inputs = {
        a = { sig = "catenary_active_thresh_out" },
      },
      outputs = {
        out = { sig = "catenary_inactive_out" },
      },
    },
    {
      id = "catenary_voltage_sub_en", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "catenary_voltage_toggle_out" },
        b = { sig = "catenary_inactive_out" },
      },
      outputs = {
        out = { sig = "catenary_voltage_sub_en_out" },
      },
    },
    {
      id = "catenary_voltage_mux", type = "NUM_SWITCHBOX",
      attrs = {
      },
      inputs = {
        a = { port = "Catenary Line Voltage [V]" },
        b = { sig = "catenary_rated_voltage_value" },
        switch = { sig = "catenary_voltage_sub_en_out" },
      },
      outputs = {
        out = { sig = "catenary_voltage_mux_out" },
      },
    },
    {
      id = "panta_up", type = "OR",
      attrs = {
      },
      inputs = {
        a = { sig = "panta1_1800_active_out" },
        b = { sig = "panta2_1800_active_out" },
      },
      outputs = {
        out = { sig = "panta_up_out" },
      },
    },
    {
      id = "catenary_voltage_sw", type = "NUM_SWITCHBOX",
      attrs = {
      },
      inputs = {
        a = { sig = "catenary_voltage_mux_out" },
        switch = { sig = "panta_up_out" },
      },
      outputs = {
        out = { sig = "catenary_voltage_sw_out" },
      },
    },
    {
      id = "speed", type = "COMPOSITE_READ_NUMBER",
      attrs = {
        channel = 9,
      },
      inputs = {
        composite = { port = "Phyics Sensor [+Z is front]" },
      },
      outputs = {
        out = { sig = "speed_out" },
      },
    },
    {
      id = "speed_raw", type = "COMPOSITE_READ_NUMBER",
      attrs = {
        channel = 7,
      },
      inputs = {
        composite = { sig = "current_src_mux_out" },
      },
      outputs = {
        out = { sig = "speed_raw_out" },
      },
    },
    {
      id = "speed_display", type = "FUNC_NUM_1",
      attrs = {
        expression = "x*3.6+1",
      },
      inputs = {
        x = { sig = "speed_raw_out" },
      },
      outputs = {
        out = { sig = "speed_display_out" },
      },
    },
    {
      id = "abs_speed", type = "ABS",
      attrs = {
      },
      inputs = {
        a = { sig = "speed_out" },
      },
      outputs = {
        out = { sig = "abs_speed_out" },
      },
    },
    {
      id = "position_delta", type = "DELTA",
      attrs = {
      },
      inputs = {
        a = { sig = "position_counter_out" },
      },
      outputs = {
        out = { sig = "position_delta_out" },
      },
    },
    {
      id = "position_changing", type = "THRESHOLD",
      attrs = {
        min = 0,
        max = 0,
      },
      inputs = {
        value = { sig = "position_delta_out" },
      },
      outputs = {
        out = { sig = "position_changing_out" },
      },
    },
    {
      id = "position_counter", type = "FUNC_NUM_3",
      attrs = {
        expression = "(x+y)%21",
      },
      inputs = {
        x = { sig = "position_counter_out" },
        y = { sig = "position_inc_sw_out" },
      },
      outputs = {
        out = { sig = "position_counter_out" },
      },
    },
    {
      id = "position_inc_sw", type = "NUM_SWITCHBOX",
      attrs = {
      },
      inputs = {
        a = { sig = "pos_inc_step_value" },
        b = { sig = "pos_hold_zero_value" },
        switch = { sig = "position_tick_pulse_out" },
      },
      outputs = {
        out = { sig = "position_inc_sw_out" },
      },
    },
    {
      id = "position_tick_pulse", type = "PULSE",
      attrs = {
        mode = "rise",
      },
      inputs = {
        a = { sig = "traction_blinker_out" },
      },
      outputs = {
        out = { sig = "position_tick_pulse_out" },
      },
    },
    {
      id = "traction_blinker", type = "BLINKER",
      attrs = {
        on_time = 0.1,
        off_time = 0.1,
      },
      inputs = {
        enable = { sig = "traction_any_active_out" },
      },
      outputs = {
        out = { sig = "traction_blinker_out" },
      },
    },
    {
      id = "pos_inc_step", type = "CONST",
      attrs = {
        value = 1,
      },
      inputs = {
      },
      outputs = {
        value = { sig = "pos_inc_step_value" },
      },
    },
    {
      id = "pos_hold_zero", type = "CONST",
      attrs = {
        value = 0,
      },
      inputs = {
      },
      outputs = {
        value = { sig = "pos_hold_zero_value" },
      },
    },
    {
      id = "cam_not", type = "NOT",
      attrs = {
      },
      inputs = {
        a = { sig = "position_changing_out" },
      },
      outputs = {
        out = { port = "cam" },
      },
    },
    {
      id = "notch_pos", type = "COMPOSITE_READ_NUMBER",
      attrs = {
        channel = 2,
      },
      inputs = {
        composite = { port = "Simple IF" },
      },
      outputs = {
        out = { sig = "notch_pos_out" },
      },
    },
    {
      id = "notch_active", type = "THRESHOLD",
      attrs = {
        min = 0,
        max = 0,
      },
      inputs = {
        value = { sig = "notch_pos_out" },
      },
      outputs = {
        out = { sig = "notch_active_out" },
      },
    },
    {
      id = "notch_eff", type = "FUNC_NUM_3",
      attrs = {
        expression = "clamp(x,0,7)*y",
      },
      inputs = {
        x = { sig = "notch_pos_out" },
        y = { sig = "notch_enable_sw_out" },
      },
      outputs = {
        out = { sig = "notch_eff_out" },
      },
    },
    {
      id = "notch_enable_sw", type = "NUM_SWITCHBOX",
      attrs = {
      },
      inputs = {
        b = { sig = "notch_mult_one_value" },
        switch = { sig = "eb_condition_out" },
      },
      outputs = {
        out = { sig = "notch_enable_sw_out" },
      },
    },
    {
      id = "notch_mult_one", type = "CONST",
      attrs = {
        value = 1,
      },
      inputs = {
      },
      outputs = {
        value = { sig = "notch_mult_one_value" },
      },
    },
    {
      id = "notch_ge1", type = "THRESHOLD",
      attrs = {
        min = 1,
        max = 7,
      },
      inputs = {
        value = { sig = "notch_eff_out" },
      },
      outputs = {
        out = { sig = "notch_ge1_out" },
      },
    },
    {
      id = "notch_ge2", type = "THRESHOLD",
      attrs = {
        min = 2,
        max = 7,
      },
      inputs = {
        value = { sig = "notch_eff_out" },
      },
      outputs = {
        out = { sig = "notch_ge2_out" },
      },
    },
    {
      id = "notch_ge3", type = "THRESHOLD",
      attrs = {
        min = 3,
        max = 7,
      },
      inputs = {
        value = { sig = "notch_eff_out" },
      },
      outputs = {
        out = { sig = "notch_ge3_out" },
      },
    },
    {
      id = "notch_ge4", type = "THRESHOLD",
      attrs = {
        min = 4,
        max = 7,
      },
      inputs = {
        value = { sig = "notch_eff_out" },
      },
      outputs = {
        out = { sig = "notch_ge4_out" },
      },
    },
    {
      id = "notch_fb", type = "COMPOSITE_READ_NUMBER",
      attrs = {
        channel = 5,
      },
      inputs = {
        composite = { sig = "current_src_mux_out" },
      },
      outputs = {
        out = { sig = "notch_fb_out" },
      },
    },
    {
      id = "notch_fb_ge1", type = "THRESHOLD",
      attrs = {
        min = 0,
        max = 0,
      },
      inputs = {
        value = { sig = "notch_fb_out" },
      },
      outputs = {
        out = { sig = "notch_fb_ge1_out" },
      },
    },
    {
      id = "notch_fb_range_low", type = "THRESHOLD",
      attrs = {
        min = 0,
        max = 13,
      },
      inputs = {
        value = { sig = "notch_fb_out" },
      },
      outputs = {
        out = { sig = "notch_fb_range_low_out" },
      },
    },
    {
      id = "notch_fb_range_high", type = "THRESHOLD",
      attrs = {
        min = 14,
        max = 20,
      },
      inputs = {
        value = { sig = "notch_fb_out" },
      },
      outputs = {
        out = { sig = "notch_fb_range_high_out" },
      },
    },
    {
      id = "notch_fb_eq14", type = "THRESHOLD",
      attrs = {
        min = 14,
        max = 14,
      },
      inputs = {
        value = { sig = "notch_fb_out" },
      },
      outputs = {
        out = { sig = "notch_fb_eq14_out" },
      },
    },
    {
      id = "notch_fb_ne14", type = "NOT",
      attrs = {
      },
      inputs = {
        a = { sig = "notch_fb_eq14_out" },
      },
      outputs = {
        out = { sig = "notch_fb_ne14_out" },
      },
    },
    {
      id = "notch_fb_zero", type = "EQUAL",
      attrs = {
        epsilon = 0.0001,
      },
      inputs = {
        b = { sig = "notch_fb_out" },
      },
      outputs = {
        out = { sig = "notch_fb_zero_out" },
      },
    },
    {
      id = "notch_fb_nonzero", type = "NOT",
      attrs = {
      },
      inputs = {
        a = { sig = "notch_fb_zero_out" },
      },
      outputs = {
        out = { sig = "notch_fb_nonzero_out" },
      },
    },
    {
      id = "regen_available", type = "THRESHOLD",
      attrs = {
        min = 0,
        max = 0,
      },
      inputs = {
        value = { sig = "notch_fb_out" },
      },
      outputs = {
        out = { sig = "regen_available_out" },
      },
    },
    {
      id = "current_sim", type = "LUA",
      attrs = {
        script_ref = "scripts/current_sim.lua",
      },
      inputs = {
        composite = { sig = "sim_input_out" },
      },
      outputs = {
        composite = { sig = "current_sim_composite" },
      },
    },
    {
      id = "sim_input", type = "COMPOSITE_WRITE_NUMBER",
      attrs = {
        count = 8,
        offset = 1,
      },
      inputs = {
        in1 = { sig = "speed_out" },
        in2 = { sig = "catenary_voltage_sw_out" },
        in3 = { sig = "position_counter_out" },
        in4 = { sig = "direction_out" },
        in5 = { sig = "notch_eff_out" },
        in6 = { sig = "current_offset_200_value" },
        in7 = { sig = "regen_bc_smooth_out" },
        in8 = { sig = "regen_bc_target_out" },
        inc = { sig = "traction_status_bool_out" },
      },
      outputs = {
        out = { sig = "sim_input_out" },
      },
    },
    {
      id = "current_src_mux", type = "COMPOSITE_SWITCHBOX",
      attrs = {
      },
      inputs = {
        a = { sig = "regen_current_write_out" },
        b = { sig = "current_sim_composite" },
        switch = { sig = "eb_condition_out" },
      },
      outputs = {
        out = { sig = "current_src_mux_out" },
      },
    },
    {
      id = "motor_current", type = "COMPOSITE_READ_NUMBER",
      attrs = {
        channel = 1,
      },
      inputs = {
        composite = { sig = "current_src_mux_out" },
      },
      outputs = {
        out = { sig = "motor_current_out" },
      },
    },
    {
      id = "motor_current_in_range", type = "THRESHOLD",
      attrs = {
        min = -200000,
        max = 200000,
      },
      inputs = {
        value = { sig = "motor_current_out" },
      },
      outputs = {
        out = { sig = "motor_current_in_range_out" },
      },
    },
    {
      id = "motor_current_positive", type = "GREATER_THAN",
      attrs = {
      },
      inputs = {
        a = { sig = "motor_current_out" },
      },
      outputs = {
        out = { sig = "motor_current_positive_out" },
      },
    },
    {
      id = "motor_current_oor", type = "NOT",
      attrs = {
      },
      inputs = {
        a = { sig = "motor_current_in_range_out" },
      },
      outputs = {
        out = { sig = "motor_current_oor_out" },
      },
    },
    {
      id = "startup_delay", type = "CAPACITOR",
      attrs = {
        charge_time = 5,
        discharge_time = 0,
      },
      inputs = {
      },
      outputs = {
        out = { sig = "startup_delay_out" },
      },
    },
    {
      id = "power_cut_set", type = "OR",
      attrs = {
      },
      inputs = {
        a = { sig = "startup_delay_out" },
        b = { sig = "motor_current_oor_out" },
      },
      outputs = {
        out = { sig = "power_cut_set_out" },
      },
    },
    {
      id = "power_cut_latch", type = "SR_LATCH",
      attrs = {
      },
      inputs = {
        r = { sig = "power_cut_reset_out" },
        s = { sig = "power_cut_set_out" },
      },
      outputs = {
        q = { sig = "power_cut_latch_q" },
      },
    },
    {
      id = "power_cut_reset", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "notch_active_out" },
        b = { sig = "regen_flag_inv_out" },
      },
      outputs = {
        out = { sig = "power_cut_reset_out" },
      },
    },
    {
      id = "danryu_not", type = "NOT",
      attrs = {
      },
      inputs = {
        a = { sig = "motor_current_positive_out" },
      },
      outputs = {
        out = { port = "DANRYU" },
      },
    },
    {
      id = "regen_flag", type = "COMPOSITE_READ_BOOLEAN",
      attrs = {
        channel = 18,
      },
      inputs = {
        composite = { port = "Simple IF" },
      },
      outputs = {
        out = { sig = "regen_flag_out" },
      },
    },
    {
      id = "regen_flag_inv", type = "NOT",
      attrs = {
      },
      inputs = {
        a = { sig = "regen_flag_out" },
      },
      outputs = {
        out = { sig = "regen_flag_inv_out" },
      },
    },
    {
      id = "overspeed", type = "GREATER_THAN",
      attrs = {
      },
      inputs = {
        a = { sig = "abs_speed_out" },
        b = { sig = "overspeed_threshold_out" },
      },
      outputs = {
        out = { sig = "overspeed_out" },
      },
    },
    {
      id = "overspeed_threshold", type = "PROPERTY_NUMBER",
      attrs = {
        value = 32,
        n = "Over Speed Th. [m/s]",
      },
      inputs = {
      },
      outputs = {
        out = { sig = "overspeed_threshold_out" },
      },
    },
    {
      id = "direction_nonzero", type = "THRESHOLD",
      attrs = {
        min = 0,
        max = 0,
      },
      inputs = {
        value = { sig = "direction_out" },
      },
      outputs = {
        out = { sig = "direction_nonzero_out" },
      },
    },
    {
      id = "eb_condition", type = "BOOL_FUNC_8",
      attrs = {
        expression = "x|y|z|w|a|b|c|d",
      },
      inputs = {
        x = { port = "Controller Stop" },
        y = { sig = "power_cut_latch_q" },
        z = { sig = "direction_nonzero_out" },
        w = { sig = "overspeed_out" },
        a = { sig = "brake_below_min_out" },
      },
      outputs = {
        out = { sig = "eb_condition_out" },
      },
    },
    {
      id = "bc_target_raw", type = "COMPOSITE_READ_NUMBER",
      attrs = {
        channel = 3,
      },
      inputs = {
        composite = { sig = "current_src_mux_out" },
      },
      outputs = {
        out = { sig = "bc_target_raw_out" },
      },
    },
    {
      id = "bc_target_smooth", type = "FUNC_NUM_3",
      attrs = {
        expression = "(x*0.2)+(y*0.8)",
      },
      inputs = {
        x = { sig = "bc_target_raw_out" },
        y = { sig = "bc_target_smooth_out" },
      },
      outputs = {
        out = { sig = "bc_target_smooth_out" },
      },
    },
    {
      id = "speed_w_read", type = "COMPOSITE_READ_NUMBER",
      attrs = {
        channel = 4,
      },
      inputs = {
        composite = { sig = "current_src_mux_out" },
      },
      outputs = {
        out = { port = "W" },
      },
    },
    {
      id = "power_limit_current", type = "PROPERTY_NUMBER",
      attrs = {
        value = 210,
        n = "Power Limit Current [A]",
      },
      inputs = {
      },
      outputs = {
        out = { sig = "power_limit_current_out" },
      },
    },
    {
      id = "brake_limit_current", type = "PROPERTY_NUMBER",
      attrs = {
        value = 290,
        n = "Brake Limit@320kPa [A]",
      },
      inputs = {
      },
      outputs = {
        out = { sig = "brake_limit_current_out" },
      },
    },
    {
      id = "traction_status_bool", type = "COMPOSITE_WRITE_BOOLEAN",
      attrs = {
        count = 6,
        offset = 1,
      },
      inputs = {
        in1 = { sig = "traction_phase1_latch_q" },
        in2 = { sig = "traction_phase2_latch_q" },
        in3 = { sig = "regen_latch_q" },
        in4 = { sig = "notch_ge1_out" },
        in5 = { sig = "low_bc_with_regen_flag_out" },
        in6 = { sig = "field_current_excess_cond_out" },
      },
      outputs = {
        out = { sig = "traction_status_bool_out" },
      },
    },
    {
      id = "brake_current_fb", type = "COMPOSITE_READ_NUMBER",
      attrs = {
        channel = 6,
      },
      inputs = {
        composite = { sig = "current_src_mux_out" },
      },
      outputs = {
        out = { sig = "brake_current_fb_out" },
      },
    },
    {
      id = "brake_current_high", type = "GREATER_THAN",
      attrs = {
      },
      inputs = {
        a = { sig = "brake_current_fb_out" },
        b = { sig = "brake_limit_sw_out" },
      },
      outputs = {
        out = { sig = "brake_current_high_out" },
      },
    },
    {
      id = "brake_current_above_300", type = "GREATER_THAN",
      attrs = {
      },
      inputs = {
        a = { sig = "brake_current_fb_out" },
        b = { sig = "brake_limit_300_b_value" },
      },
      outputs = {
        out = { sig = "brake_current_above_300_out" },
      },
    },
    {
      id = "brake_limit_300_b", type = "CONST",
      attrs = {
        value = 300,
      },
      inputs = {
      },
      outputs = {
        value = { sig = "brake_limit_300_b_value" },
      },
    },
    {
      id = "brake_limit_300_const", type = "CONST",
      attrs = {
        value = 300,
      },
      inputs = {
      },
      outputs = {
        value = { sig = "brake_limit_300_const_value" },
      },
    },
    {
      id = "brake_limit_400", type = "CONST",
      attrs = {
        value = 400,
      },
      inputs = {
      },
      outputs = {
        value = { sig = "brake_limit_400_value" },
      },
    },
    {
      id = "brake_min_pressure", type = "CONST",
      attrs = {
        value = 4,
      },
      inputs = {
      },
      outputs = {
        value = { sig = "brake_min_pressure_value" },
      },
    },
    {
      id = "brake_below_min", type = "LESS_THAN",
      attrs = {
      },
      inputs = {
        a = { sig = "brake_pressure_sw_out" },
        b = { sig = "brake_min_pressure_value" },
      },
      outputs = {
        out = { sig = "brake_below_min_out" },
      },
    },
    {
      id = "brake_pressure_sw", type = "NUM_SWITCHBOX",
      attrs = {
      },
      inputs = {
        a = { port = "BP [atm]" },
        b = { sig = "ecb_pressure_sw_out" },
        switch = { sig = "sap_ecb_toggle_out" },
      },
      outputs = {
        out = { sig = "brake_pressure_sw_out" },
      },
    },
    {
      id = "sap_ecb_toggle", type = "PROPERTY_TOGGLE",
      attrs = {
        label = "",
        on_label = "SAP",
        off_label = "ECB",
        n = "SAP or ECB",
      },
      inputs = {
      },
      outputs = {
        out = { sig = "sap_ecb_toggle_out" },
      },
    },
    {
      id = "ecb_pressure_sw", type = "NUM_SWITCHBOX",
      attrs = {
      },
      inputs = {
        a = { sig = "ecb_offset_eb_active_value" },
        b = { sig = "ecb_offset_eb_inactive_value" },
        switch = { sig = "eb_signal_out" },
      },
      outputs = {
        out = { sig = "ecb_pressure_sw_out" },
      },
    },
    {
      id = "eb_signal", type = "COMPOSITE_READ_BOOLEAN",
      attrs = {
        channel = 1,
      },
      inputs = {
        composite = { port = "Simple IF" },
      },
      outputs = {
        out = { sig = "eb_signal_out" },
      },
    },
    {
      id = "ecb_offset_eb_active", type = "CONST",
      attrs = {
        value = 0,
      },
      inputs = {
      },
      outputs = {
        value = { sig = "ecb_offset_eb_active_value" },
      },
    },
    {
      id = "ecb_offset_eb_inactive", type = "CONST",
      attrs = {
        value = 5,
      },
      inputs = {
      },
      outputs = {
        value = { sig = "ecb_offset_eb_inactive_value" },
      },
    },
    {
      id = "sap_raw", type = "COMPOSITE_READ_NUMBER",
      attrs = {
        channel = 1,
      },
      inputs = {
        composite = { port = "Simple IF" },
      },
      outputs = {
        out = { sig = "sap_raw_out" },
      },
    },
    {
      id = "forward_signal", type = "COMPOSITE_READ_BOOLEAN",
      attrs = {
        channel = 16,
      },
      inputs = {
        composite = { port = "Simple IF" },
      },
      outputs = {
        out = { sig = "forward_signal_out" },
      },
    },
    {
      id = "backward_signal", type = "COMPOSITE_READ_BOOLEAN",
      attrs = {
        channel = 17,
      },
      inputs = {
        composite = { port = "Simple IF" },
      },
      outputs = {
        out = { sig = "backward_signal_out" },
      },
    },
    {
      id = "direction", type = "SUBTRACT",
      attrs = {
      },
      inputs = {
        a = { sig = "forward_flag_sw_out" },
        b = { sig = "backward_flag_sw_out" },
      },
      outputs = {
        out = { sig = "direction_out" },
      },
    },
    {
      id = "forward_flag_sw", type = "NUM_SWITCHBOX",
      attrs = {
      },
      inputs = {
        a = { sig = "direction_flag_one_value" },
        b = { sig = "direction_flag_zero_value" },
        switch = { sig = "forward_signal_out" },
      },
      outputs = {
        out = { sig = "forward_flag_sw_out" },
      },
    },
    {
      id = "backward_flag_sw", type = "NUM_SWITCHBOX",
      attrs = {
      },
      inputs = {
        a = { sig = "direction_flag_one_value" },
        b = { sig = "direction_flag_zero_value" },
        switch = { sig = "backward_signal_out" },
      },
      outputs = {
        out = { sig = "backward_flag_sw_out" },
      },
    },
    {
      id = "direction_flag_one", type = "CONST",
      attrs = {
        value = 1,
      },
      inputs = {
      },
      outputs = {
        value = { sig = "direction_flag_one_value" },
      },
    },
    {
      id = "direction_flag_zero", type = "CONST",
      attrs = {
        value = 0,
      },
      inputs = {
      },
      outputs = {
        value = { sig = "direction_flag_zero_value" },
      },
    },
    {
      id = "sap_pressure_sw", type = "NUM_SWITCHBOX",
      attrs = {
      },
      inputs = {
        a = { port = "SAP [atm]" },
        b = { sig = "ecb_sap_pressure_out" },
        switch = { sig = "sap_ecb_toggle_out" },
      },
      outputs = {
        out = { sig = "sap_pressure_sw_out" },
      },
    },
    {
      id = "ecb_sap_pressure", type = "FUNC_NUM_3",
      attrs = {
        expression = "clamp(x+(5-y)*7,0,36)/8+1",
      },
      inputs = {
        x = { sig = "sap_raw_out" },
        y = { sig = "ecb_pressure_sw_out" },
      },
      outputs = {
        out = { sig = "ecb_sap_pressure_out" },
      },
    },
    {
      id = "traction_phase1_latch", type = "SR_LATCH",
      attrs = {
      },
      inputs = {
        r = { sig = "traction_phase1_reset_out" },
        s = { sig = "traction_phase1_set_out" },
      },
      outputs = {
        q = { sig = "traction_phase1_latch_q" },
        not_q = { sig = "traction_phase1_latch_not_q" },
      },
    },
    {
      id = "traction_phase1_set_cond", type = "BOOL_FUNC_4",
      attrs = {
        expression = "x&y&z&w",
      },
      inputs = {
        x = { sig = "notch_ge2_out" },
        y = { sig = "notch_fb_range_low_out" },
        z = { sig = "traction_phase1_cap_out" },
        w = { sig = "current_below_limit_cap_out" },
      },
      outputs = {
        out = { sig = "traction_phase1_set_cond_out" },
      },
    },
    {
      id = "traction_phase1_cap", type = "CAPACITOR",
      attrs = {
        charge_time = 0.1,
        discharge_time = 0,
      },
      inputs = {
        enable = { sig = "traction_phase1_latch_q" },
      },
      outputs = {
        out = { sig = "traction_phase1_cap_out" },
      },
    },
    {
      id = "phase1_notch_active", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "traction_phase1_latch_q" },
        b = { sig = "notch_ge1_out" },
      },
      outputs = {
        out = { sig = "phase1_notch_active_out" },
      },
    },
    {
      id = "phase1_not_high_notch", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "traction_phase1_latch_q" },
        b = { sig = "notch_fb_ne14_out" },
      },
      outputs = {
        out = { sig = "phase1_not_high_notch_out" },
      },
    },
    {
      id = "phase1_regen_active", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "phase1_not_high_notch_out" },
        b = { sig = "regen_latch_q" },
      },
      outputs = {
        out = { sig = "phase1_regen_active_out" },
      },
    },
    {
      id = "phase1_low_bc", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "traction_phase1_latch_q" },
        b = { sig = "regen_bc_below_min_out" },
      },
      outputs = {
        out = { sig = "phase1_low_bc_out" },
      },
    },
    {
      id = "brake_limit_sw", type = "NUM_SWITCHBOX",
      attrs = {
      },
      inputs = {
        a = { sig = "brake_limit_400_value" },
        b = { sig = "brake_limit_300_const_value" },
        switch = { sig = "phase1_low_bc_out" },
      },
      outputs = {
        out = { sig = "brake_limit_sw_out" },
      },
    },
    {
      id = "brake_current_high_phase1", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "brake_current_above_300_out" },
        b = { sig = "traction_phase1_cap_out" },
      },
      outputs = {
        out = { sig = "brake_current_high_phase1_out" },
      },
    },
    {
      id = "traction_phase1_set", type = "BOOL_FUNC_4",
      attrs = {
        expression = "(x&y)|(z&w)",
      },
      inputs = {
        x = { sig = "power_with_regen_out" },
        y = { sig = "traction_phase2_latch_not_q" },
        z = { sig = "field_current_excess_pulse_out" },
        w = { sig = "traction_phase2_latch_q" },
      },
      outputs = {
        out = { sig = "traction_phase1_set_out" },
      },
    },
    {
      id = "traction_phase1_reset", type = "BOOL_FUNC_4",
      attrs = {
        expression = "x|(y&z)|w",
      },
      inputs = {
        x = { sig = "phase_reset_cond_out" },
        y = { sig = "field_current_excess_pulse_out" },
        z = { sig = "traction_phase1_cap_out" },
        w = { sig = "traction_phase2_set_cond_out" },
      },
      outputs = {
        out = { sig = "traction_phase1_reset_out" },
      },
    },
    {
      id = "traction_phase2_latch", type = "SR_LATCH",
      attrs = {
      },
      inputs = {
        r = { sig = "traction_phase2_reset_out" },
        s = { sig = "traction_phase2_set_cond_out" },
      },
      outputs = {
        q = { sig = "traction_phase2_latch_q" },
        not_q = { sig = "traction_phase2_latch_not_q" },
      },
    },
    {
      id = "traction_phase2_blinker_cond", type = "BOOL_FUNC_4",
      attrs = {
        expression = "x&y&z&w",
      },
      inputs = {
        x = { sig = "notch_ge3_out" },
        y = { sig = "notch_fb_range_high_out" },
        z = { sig = "traction_phase2_cap_out" },
        w = { sig = "current_below_limit_cap_out" },
      },
      outputs = {
        out = { sig = "traction_phase2_blinker_cond_out" },
      },
    },
    {
      id = "traction_phase2_cap", type = "CAPACITOR",
      attrs = {
        charge_time = 0.1,
        discharge_time = 0,
      },
      inputs = {
        enable = { sig = "traction_phase2_latch_q" },
      },
      outputs = {
        out = { sig = "traction_phase2_cap_out" },
      },
    },
    {
      id = "traction_phase2_set_cond", type = "BOOL_FUNC_4",
      attrs = {
        expression = "x&y&z",
      },
      inputs = {
        x = { sig = "notch_ge3_out" },
        y = { sig = "notch_fb_eq14_out" },
        z = { sig = "current_below_limit_cap_out" },
      },
      outputs = {
        out = { sig = "traction_phase2_set_cond_out" },
      },
    },
    {
      id = "traction_phase2_reset", type = "BOOL_FUNC_4",
      attrs = {
        expression = "x|(y&!(z&w))",
      },
      inputs = {
        x = { sig = "phase_reset_cond_out" },
        y = { sig = "traction_phase1_latch_q" },
        z = { sig = "notch_ge3_out" },
        w = { sig = "notch_fb_eq14_out" },
      },
      outputs = {
        out = { sig = "traction_phase2_reset_out" },
      },
    },
    {
      id = "current_below_limit", type = "LESS_THAN",
      attrs = {
      },
      inputs = {
        a = { sig = "motor_current_out" },
        b = { sig = "current_limit_sw_out" },
      },
      outputs = {
        out = { sig = "current_below_limit_out" },
      },
    },
    {
      id = "current_below_limit_cap", type = "CAPACITOR",
      attrs = {
        charge_time = 0.1,
        discharge_time = 0,
      },
      inputs = {
        enable = { sig = "current_below_limit_out" },
      },
      outputs = {
        out = { sig = "current_below_limit_cap_out" },
      },
    },
    {
      id = "current_limit_sw", type = "NUM_SWITCHBOX",
      attrs = {
      },
      inputs = {
        a = { sig = "current_limit_reduced_out" },
        b = { sig = "power_limit_current_out" },
        switch = { sig = "traction_phase2_latch_q" },
      },
      outputs = {
        out = { sig = "current_limit_sw_out" },
      },
    },
    {
      id = "current_limit_reduced", type = "FUNC_NUM_1",
      attrs = {
        expression = "x-20",
      },
      inputs = {
        x = { sig = "power_limit_current_out" },
      },
      outputs = {
        out = { sig = "current_limit_reduced_out" },
      },
    },
    {
      id = "traction_any_active", type = "BOOL_FUNC_8",
      attrs = {
        expression = "x|y|z|w|a|b|c|d",
      },
      inputs = {
        x = { sig = "traction_phase1_set_cond_out" },
        y = { sig = "traction_phase2_blinker_cond_out" },
        z = { sig = "regen_off_all_out" },
        w = { sig = "phase1_regen_active_out" },
      },
      outputs = {
        out = { sig = "traction_any_active_out" },
      },
    },
    {
      id = "regen_latch", type = "SR_LATCH",
      attrs = {
      },
      inputs = {
        r = { sig = "regen_reset_out" },
        s = { sig = "regen_set_cond_out" },
      },
      outputs = {
        q = { sig = "regen_latch_q" },
        not_q = { sig = "regen_latch_not_q" },
      },
    },
    {
      id = "regen_set_cond", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "traction_phase2_latch_q" },
        b = { sig = "regen_available_out" },
      },
      outputs = {
        out = { sig = "regen_set_cond_out" },
      },
    },
    {
      id = "regen_reset", type = "OR",
      attrs = {
      },
      inputs = {
        a = { sig = "phase1_notch_active_out" },
        b = { sig = "traction_all_off_out" },
      },
      outputs = {
        out = { sig = "regen_reset_out" },
      },
    },
    {
      id = "regen_not_available", type = "NOT",
      attrs = {
      },
      inputs = {
        a = { sig = "notch_fb_ge1_out" },
      },
      outputs = {
        out = { sig = "regen_not_available_out" },
      },
    },
    {
      id = "traction_all_off", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "traction_phase1_latch_not_q" },
        b = { sig = "traction_phase2_latch_not_q" },
      },
      outputs = {
        out = { sig = "traction_all_off_out" },
      },
    },
    {
      id = "regen_off_all", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "regen_not_available_out" },
        b = { sig = "traction_all_off_out" },
      },
      outputs = {
        out = { sig = "regen_off_all_out" },
      },
    },
    {
      id = "power_with_regen", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "notch_ge1_out" },
        b = { sig = "notch_fb_ge1_out" },
      },
      outputs = {
        out = { sig = "power_with_regen_out" },
      },
    },
    {
      id = "no_power_notch", type = "NOT",
      attrs = {
      },
      inputs = {
        a = { sig = "notch_ge1_out" },
      },
      outputs = {
        out = { sig = "no_power_notch_out" },
      },
    },
    {
      id = "field_current_excess_cond", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "brake_current_high_out" },
        b = { sig = "no_power_notch_out" },
      },
      outputs = {
        out = { sig = "field_current_excess_cond_out" },
      },
    },
    {
      id = "field_current_excess_blinker", type = "BLINKER",
      attrs = {
        on_time = 0.1,
        off_time = 0.4,
      },
      inputs = {
        enable = { sig = "field_current_excess_cond_out" },
      },
      outputs = {
        out = { sig = "field_current_excess_blinker_out" },
      },
    },
    {
      id = "field_current_excess_pulse", type = "PULSE",
      attrs = {
        mode = "rise",
      },
      inputs = {
        a = { sig = "field_current_excess_blinker_out" },
      },
      outputs = {
        out = { sig = "field_current_excess_pulse_out" },
      },
    },
    {
      id = "coasting_cond", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "neutral_cond_out" },
        b = { sig = "regen_latch_not_q" },
      },
      outputs = {
        out = { sig = "coasting_cond_out" },
      },
    },
    {
      id = "current_near_zero", type = "THRESHOLD",
      attrs = {
        min = -50,
        max = 50,
      },
      inputs = {
        value = { sig = "motor_current_out" },
      },
      outputs = {
        out = { sig = "current_near_zero_out" },
      },
    },
    {
      id = "no_notch_no_regen_brake_demand", type = "NOR",
      attrs = {
      },
      inputs = {
        a = { sig = "notch_ge1_out" },
        b = { sig = "low_bc_with_regen_flag_out" },
      },
      outputs = {
        out = { sig = "no_notch_no_regen_brake_demand_out" },
      },
    },
    {
      id = "neutral_cond", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "current_near_zero_out" },
        b = { sig = "no_notch_no_regen_brake_demand_out" },
      },
      outputs = {
        out = { sig = "neutral_cond_out" },
      },
    },
    {
      id = "phase_reset_cond", type = "OR",
      attrs = {
      },
      inputs = {
        a = { sig = "coasting_cond_out" },
        b = { sig = "regen_pulse_regen_flag_off_out" },
      },
      outputs = {
        out = { sig = "phase_reset_cond_out" },
      },
    },
    {
      id = "regen_pulse_regen_flag_off", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "field_current_excess_pulse_out" },
        b = { sig = "regen_flag_inv_out" },
      },
      outputs = {
        out = { sig = "regen_pulse_regen_flag_off_out" },
      },
    },
    {
      id = "regen_bc_target", type = "FUNC_NUM_1",
      attrs = {
        expression = "-floor((x-1)*2)/7.2",
      },
      inputs = {
        x = { sig = "sap_pressure_sw_out" },
      },
      outputs = {
        out = { sig = "regen_bc_target_out" },
      },
    },
    {
      id = "regen_bc_smooth", type = "FUNC_NUM_3",
      attrs = {
        expression = "min(clamp(x,y-0.1,y+0.02),0)",
      },
      inputs = {
        x = { sig = "regen_bc_sw_out" },
        y = { sig = "regen_bc_smooth_out" },
      },
      outputs = {
        out = { sig = "regen_bc_smooth_out" },
      },
    },
    {
      id = "regen_bc_sw", type = "NUM_SWITCHBOX",
      attrs = {
      },
      inputs = {
        a = { sig = "regen_bc_zero_value" },
        b = { sig = "regen_bc_target_out" },
        switch = { sig = "regen_bc_enable_out" },
      },
      outputs = {
        out = { sig = "regen_bc_sw_out" },
      },
    },
    {
      id = "regen_bc_zero", type = "CONST",
      attrs = {
        value = 0,
      },
      inputs = {
      },
      outputs = {
        value = { sig = "regen_bc_zero_value" },
      },
    },
    {
      id = "regen_bc_below_min", type = "LESS_THAN",
      attrs = {
      },
      inputs = {
        a = { sig = "regen_bc_smooth_out" },
        b = { sig = "regen_bc_min_value" },
      },
      outputs = {
        out = { sig = "regen_bc_below_min_out" },
      },
    },
    {
      id = "regen_bc_min", type = "CONST",
      attrs = {
        value = -0.1,
      },
      inputs = {
      },
      outputs = {
        value = { sig = "regen_bc_min_value" },
      },
    },
    {
      id = "regen_bc_enable", type = "OR",
      attrs = {
      },
      inputs = {
        a = { sig = "regen_delay_cap_out" },
        b = { sig = "regen_flag_inv_out" },
      },
      outputs = {
        out = { sig = "regen_bc_enable_out" },
      },
    },
    {
      id = "regen_delay_cap", type = "CAPACITOR",
      attrs = {
        charge_time = 0.5,
        discharge_time = 10,
      },
      inputs = {
        enable = { sig = "brake_current_high_phase1_out" },
      },
      outputs = {
        out = { sig = "regen_delay_cap_out" },
      },
    },
    {
      id = "bc_target_below_min", type = "LESS_THAN",
      attrs = {
      },
      inputs = {
        a = { sig = "regen_bc_target_out" },
        b = { sig = "bc_target_min_value" },
      },
      outputs = {
        out = { sig = "bc_target_below_min_out" },
      },
    },
    {
      id = "bc_target_min", type = "CONST",
      attrs = {
        value = -0.05,
      },
      inputs = {
      },
      outputs = {
        value = { sig = "bc_target_min_value" },
      },
    },
    {
      id = "low_bc_with_regen_flag", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "bc_target_below_min_out" },
        b = { sig = "regen_flag_out" },
      },
      outputs = {
        out = { sig = "low_bc_with_regen_flag_out" },
      },
    },
    {
      id = "regen_current", type = "FUNC_NUM_1",
      attrs = {
        expression = "max(-x,0)",
      },
      inputs = {
        x = { sig = "regen_bc_target_out" },
      },
      outputs = {
        out = { sig = "regen_current_out" },
      },
    },
    {
      id = "regen_current_write", type = "COMPOSITE_WRITE_NUMBER",
      attrs = {
        count = 1,
        offset = 7,
      },
      inputs = {
        in1 = { sig = "regen_current_out" },
      },
      outputs = {
        out = { sig = "regen_current_write_out" },
      },
    },
    {
      id = "current_offset_200", type = "CONST",
      attrs = {
        value = 200,
      },
      inputs = {
      },
      outputs = {
        value = { sig = "current_offset_200_value" },
      },
    },
    {
      id = "panta1_latch", type = "SR_LATCH",
      attrs = {
      },
      inputs = {
        r = { sig = "panta1_down_signal_out" },
        s = { sig = "panta1_up_signal_out" },
      },
      outputs = {
        q = { sig = "panta1_latch_q" },
        not_q = { sig = "panta1_latch_not_q" },
      },
    },
    {
      id = "panta2_latch", type = "SR_LATCH",
      attrs = {
      },
      inputs = {
        r = { sig = "panta2_down_signal_out" },
        s = { sig = "panta2_up_signal_out" },
      },
      outputs = {
        q = { sig = "panta2_latch_q" },
        not_q = { sig = "panta2_latch_not_q" },
      },
    },
    {
      id = "panta1_en_latch", type = "SR_LATCH",
      attrs = {
      },
      inputs = {
        r = { sig = "panta_all_down_signal_out" },
        s = { sig = "panta1_set_cond_out" },
      },
      outputs = {
        q = { sig = "panta1_en_latch_q" },
      },
    },
    {
      id = "panta2_en_latch", type = "SR_LATCH",
      attrs = {
      },
      inputs = {
        r = { sig = "panta_all_down_signal_out" },
        s = { sig = "panta2_set_cond_out" },
      },
      outputs = {
        q = { sig = "panta2_en_latch_q" },
      },
    },
    {
      id = "panta1_set_cond", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "panta1_latch_not_q" },
        b = { sig = "panta_enable_signal_out" },
      },
      outputs = {
        out = { sig = "panta1_set_cond_out" },
      },
    },
    {
      id = "panta2_set_cond", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "panta2_latch_not_q" },
        b = { sig = "panta_enable_signal_out" },
      },
      outputs = {
        out = { sig = "panta2_set_cond_out" },
      },
    },
    {
      id = "panta_enable_signal", type = "COMPOSITE_READ_BOOLEAN",
      attrs = {
        channel = 6,
      },
      inputs = {
        composite = { port = "Extended IF" },
      },
      outputs = {
        out = { sig = "panta_enable_signal_out" },
      },
    },
    {
      id = "panta_all_down_signal", type = "COMPOSITE_READ_BOOLEAN",
      attrs = {
        channel = 7,
      },
      inputs = {
        composite = { port = "Extended IF" },
      },
      outputs = {
        out = { sig = "panta_all_down_signal_out" },
      },
    },
    {
      id = "panta1_up_signal", type = "COMPOSITE_READ_BOOLEAN",
      attrs = {
        channel = 4,
      },
      inputs = {
        composite = { port = "Extended IF" },
      },
      outputs = {
        out = { sig = "panta1_up_signal_out" },
      },
    },
    {
      id = "panta1_down_signal", type = "COMPOSITE_READ_BOOLEAN",
      attrs = {
        channel = 5,
      },
      inputs = {
        composite = { port = "Extended IF" },
      },
      outputs = {
        out = { sig = "panta1_down_signal_out" },
      },
    },
    {
      id = "panta2_up_signal", type = "COMPOSITE_READ_BOOLEAN",
      attrs = {
        channel = 8,
      },
      inputs = {
        composite = { port = "Extended IF" },
      },
      outputs = {
        out = { sig = "panta2_up_signal_out" },
      },
    },
    {
      id = "panta2_down_signal", type = "COMPOSITE_READ_BOOLEAN",
      attrs = {
        channel = 9,
      },
      inputs = {
        composite = { port = "Extended IF" },
      },
      outputs = {
        out = { sig = "panta2_down_signal_out" },
      },
    },
    {
      id = "panta_height_type", type = "PROPERTY_DROPDOWN",
      attrs = {
        name = "Panta Height (Type)",
      },
      inputs = {
      },
      outputs = {
        out = { sig = "panta_height_type_out" },
      },
    },
    {
      id = "panta1_height_sw", type = "NUM_SWITCHBOX",
      attrs = {
      },
      inputs = {
        a = { sig = "panta_height_type_out" },
        b = { sig = "panta_default_height_value" },
        switch = { sig = "panta1_1800_active_out" },
      },
      outputs = {
        out = { sig = "panta1_height_sw_out" },
      },
    },
    {
      id = "panta2_height_sw", type = "NUM_SWITCHBOX",
      attrs = {
      },
      inputs = {
        a = { sig = "panta_height_type_out" },
        b = { sig = "panta_default_height_value" },
        switch = { sig = "panta2_1800_active_out" },
      },
      outputs = {
        out = { sig = "panta2_height_sw_out" },
      },
    },
    {
      id = "panta_default_height", type = "CONST",
      attrs = {
        value = 0.02,
      },
      inputs = {
      },
      outputs = {
        value = { sig = "panta_default_height_value" },
      },
    },
    {
      id = "mtype_toggle", type = "PROPERTY_TOGGLE",
      attrs = {
        label = "",
        on_label = "1900",
        off_label = "1800",
        n = "M type",
      },
      inputs = {
      },
      outputs = {
        out = { sig = "mtype_toggle_out" },
      },
    },
    {
      id = "is_1800_type", type = "NOT",
      attrs = {
      },
      inputs = {
        a = { sig = "mtype_toggle_out" },
      },
      outputs = {
        out = { sig = "is_1800_type_out" },
      },
    },
    {
      id = "panta1_1800_active", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "panta1_en_latch_q" },
        b = { sig = "is_1800_type_out" },
      },
      outputs = {
        out = { sig = "panta1_1800_active_out" },
      },
    },
    {
      id = "panta2_1800_active", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "panta2_en_latch_q" },
        b = { sig = "is_1800_type_out" },
      },
      outputs = {
        out = { sig = "panta2_1800_active_out" },
      },
    },
    {
      id = "momelink_1800_out", type = "COMPOSITE_WRITE_NUMBER",
      attrs = {
        count = 2,
        offset = 1,
      },
      inputs = {
        in1 = { sig = "bc_pressure_norm_out" },
        in2 = { sig = "bc_target_smooth_out" },
        inc = { sig = "momelink_1900_out_out" },
      },
      outputs = {
        out = { sig = "momelink_1800_out_out" },
      },
    },
    {
      id = "bc_pressure_norm", type = "FUNC_NUM_1",
      attrs = {
        expression = "max(x-1.45,0)/3.02",
      },
      inputs = {
        x = { port = "BC [atm abs]" },
      },
      outputs = {
        out = { sig = "bc_pressure_norm_out" },
      },
    },
    {
      id = "unit_type_code", type = "COMPOSITE_READ_NUMBER",
      attrs = {
        channel = 15,
      },
      inputs = {
        composite = { port = "Momelink inner unit" },
      },
      outputs = {
        out = { sig = "unit_type_code_out" },
      },
    },
    {
      id = "type_is_1911", type = "THRESHOLD",
      attrs = {
        min = 1911,
        max = 1911,
      },
      inputs = {
        value = { sig = "unit_type_code_out" },
      },
      outputs = {
        out = { sig = "type_is_1911_out" },
      },
    },
    {
      id = "type_id_1911", type = "CONST",
      attrs = {
        value = 1911,
      },
      inputs = {
      },
      outputs = {
        value = { sig = "type_id_1911_value" },
      },
    },
    {
      id = "const_35", type = "CONST",
      attrs = {
        value = 35,
      },
      inputs = {
      },
      outputs = {
        value = { sig = "const_35_value" },
      },
    },
    {
      id = "momelink_ch26", type = "COMPOSITE_READ_NUMBER",
      attrs = {
        channel = 26,
      },
      inputs = {
        composite = { port = "Momelink inner unit" },
      },
      outputs = {
        out = { sig = "momelink_ch26_out" },
      },
    },
    {
      id = "momelink_1900_out", type = "COMPOSITE_WRITE_NUMBER",
      attrs = {
        count = 1,
        offset = 1,
      },
      inputs = {
        in1 = { sig = "bc_pressure_norm_out" },
        in2 = { sig = "momelink_ch26_out" },
        in15 = { sig = "type_id_1911_value" },
        in22 = { sig = "const_35_value" },
        in23 = { sig = "catenary_voltage_sw_out" },
        in24 = { sig = "motor_current_out" },
        in25 = { sig = "speed_display_out" },
        in26 = { sig = "bc_target_smooth_out" },
      },
      outputs = {
        out = { sig = "momelink_1900_out_out" },
      },
    },
    {
      id = "momelink_1900_select", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "type_is_1911_out" },
        b = { sig = "mtype_toggle_out" },
      },
      outputs = {
        out = { sig = "momelink_1900_select_out" },
      },
    },
    {
      id = "momelink_version_sw", type = "COMPOSITE_SWITCHBOX",
      attrs = {
      },
      inputs = {
        a = { sig = "momelink_1900_out_out" },
        b = { sig = "momelink_1800_out_out" },
        switch = { sig = "momelink_1900_select_out" },
      },
      outputs = {
        out = { port = "Momelink-A" },
      },
    },
    {
      id = "rolling_status_bool_write", type = "COMPOSITE_WRITE_BOOLEAN",
      attrs = {
        count = 8,
        offset = 1,
      },
      inputs = {
        in1 = { sig = "power_cut_latch_q" },
        in5 = { sig = "panta1_1800_latched_out" },
        in6 = { sig = "panta1_1800_active_out" },
        in7 = { sig = "panta2_1800_latched_out" },
        in8 = { sig = "panta2_1800_active_out" },
      },
      outputs = {
        out = { sig = "rolling_status_bool_write_out" },
      },
    },
    {
      id = "panta1_1800_latched", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "panta1_latch_q" },
        b = { sig = "is_1800_type_out" },
      },
      outputs = {
        out = { sig = "panta1_1800_latched_out" },
      },
    },
    {
      id = "panta2_1800_latched", type = "AND",
      attrs = {
      },
      inputs = {
        a = { sig = "panta2_latch_q" },
        b = { sig = "is_1800_type_out" },
      },
      outputs = {
        out = { sig = "panta2_1800_latched_out" },
      },
    },
    {
      id = "momelink_src_mux", type = "COMPOSITE_SWITCHBOX",
      attrs = {
      },
      inputs = {
        a = { port = "Momelink inner unit" },
        b = { sig = "momelink_1900_out_out" },
        switch = { sig = "momelink_1900_select_out" },
      },
      outputs = {
        out = { sig = "momelink_src_mux_out" },
      },
    },
    {
      id = "momelink_ch24", type = "COMPOSITE_READ_NUMBER",
      attrs = {
        channel = 24,
      },
      inputs = {
        composite = { sig = "momelink_src_mux_out" },
      },
      outputs = {
        out = { sig = "momelink_ch24_out" },
      },
    },
    {
      id = "momelink_ch23", type = "COMPOSITE_READ_NUMBER",
      attrs = {
        channel = 23,
      },
      inputs = {
        composite = { sig = "momelink_src_mux_out" },
      },
      outputs = {
        out = { sig = "momelink_ch23_out" },
      },
    },
    {
      id = "bc_pressure_kpa", type = "FUNC_NUM_1",
      attrs = {
        expression = "max((x-1)*101.315,0)",
      },
      inputs = {
        x = { port = "BC [atm abs]" },
      },
      outputs = {
        out = { sig = "bc_pressure_kpa_out" },
      },
    },
    {
      id = "bc_target_read", type = "COMPOSITE_READ_NUMBER",
      attrs = {
        channel = 25,
      },
      inputs = {
        composite = { sig = "momelink_src_mux_out" },
      },
      outputs = {
        out = { port = "BC target [atm]" },
      },
    },
    {
      id = "rolling_status_write", type = "COMPOSITE_WRITE_NUMBER",
      attrs = {
        count = 8,
        offset = 1,
      },
      inputs = {
        in2 = { sig = "bc_pressure_kpa_out" },
        in3 = { sig = "momelink_ch24_out" },
        in5 = { sig = "momelink_ch23_out" },
        in6 = { sig = "panta1_height_sw_out" },
        in7 = { sig = "panta2_height_sw_out" },
        in8 = { port = "MR [atm abs]" },
        inc = { sig = "rolling_status_bool_write_out" },
      },
      outputs = {
        out = { port = "Rolling Stock Status" },
      },
    },
  },
}
